routes:

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: 'tag:-hash-zh'

  /zh/:
    permalink: /zh/{slug}/
    template: index-zh
    filter: 'tag:hash-zh'
    data: tag.zh-meta

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
